{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d874266f-b45a-4da3-8763-8c269ccecc7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import statsmodels.api as sm\n",
    "from sklearn.metrics import r2_score\n",
    "import seaborn as sns\n",
    "import statsmodels.api as sm\n",
    "\n",
    "def fit_ols(x, y):\n",
    "    \"\"\"Fits OLS regression and returns model and predicted values.\"\"\"\n",
    "    X_const = sm.add_constant(x)\n",
    "    model = sm.OLS(y, X_const).fit()\n",
    "    y_pred = model.predict(X_const)\n",
    "    return model, y_pred\n",
    "\n",
    "def plot_scatter_with_line(x, y, y_pred, r2, title=\"Scatter with Regression\", xlabel=\"X\", ylabel=\"Y\"):\n",
    "    \"\"\"Plots scatter plot and regression line with R^2.\"\"\"\n",
    "    plt.figure(figsize=(6,4))\n",
    "    plt.scatter(x, y, label=\"Data\")\n",
    "    plt.plot(x, y_pred, color='red', label=f\"Regression line\\n$R^2={r2:.2f}$\")\n",
    "    plt.xlabel(xlabel)\n",
    "    plt.ylabel(ylabel)\n",
    "    plt.title(title)\n",
    "    plt.legend()\n",
    "    plt.show()\n",
    "\n",
    "def scatter_with_regression(x, y, title=\"Scatter with Regression\", xlabel=\"X\", ylabel=\"Y\"):\n",
    "    model, y_pred = fit_ols(x, y)\n",
    "    r2 = r2_score(y, y_pred)\n",
    "    plot_scatter_with_line(x, y, y_pred, r2, title, xlabel, ylabel)\n",
    "    return model\n",
    "    \n",
    "def scatter_with_regression_zoom(x, y, title=\"Scatter with Regression\", \n",
    "                                 xlabel=\"X\", ylabel=\"Y\", zoom=(0,0)):\n",
    "    \"\"\"\n",
    "    Fit OLS on full data, but optionally zoom in by removing extremes from plotting.\n",
    "    zoom = (n_x, n_y) removes n_x extreme points from x and n_y from y (top or bottom)\n",
    "    \"\"\"\n",
    "    # If x is a single-column DataFrame, convert to Series\n",
    "    if isinstance(x, pd.DataFrame) and x.shape[1] == 1:\n",
    "        x = x.iloc[:,0]\n",
    "        \n",
    "    # Fit full model\n",
    "    model, y_pred = fit_ols(x, y)\n",
    "    \n",
    "    # Determine indices to keep\n",
    "    idx_x = np.arange(len(x))\n",
    "    idx_y = np.arange(len(y))\n",
    "    \n",
    "    if zoom[0] > 0:\n",
    "        # Remove n_x most extreme x values (top or bottom)\n",
    "        sorted_x_idx = np.argsort(x)\n",
    "        idx_x = sorted_x_idx[zoom[0]:-zoom[0]] if zoom[0]*2 < len(x) else sorted_x_idx\n",
    "    if zoom[1] > 0:\n",
    "        # Remove n_y most extreme y values (top or bottom)\n",
    "        sorted_y_idx = np.argsort(y)\n",
    "        idx_y = sorted_y_idx[zoom[1]:-zoom[1]] if zoom[1]*2 < len(y) else sorted_y_idx\n",
    "    \n",
    "    # Intersection of indices to keep\n",
    "    keep_idx = np.intersect1d(idx_x, idx_y)\n",
    "    \n",
    "    # Filter for plotting only\n",
    "    x_plot = x.iloc[keep_idx] if isinstance(x, pd.Series) else x[keep_idx]\n",
    "    y_plot = y.iloc[keep_idx] if isinstance(y, pd.Series) else y[keep_idx]\n",
    "    y_pred_plot = y_pred[keep_idx]\n",
    "    \n",
    "    # Plot\n",
    "    r2 = r2_score(y, y_pred)\n",
    "    plot_scatter_with_line(x_plot, y_plot, y_pred_plot, r2, title=title, xlabel=xlabel, ylabel=ylabel)\n",
    "    \n",
    "    return model\n",
    "\n",
    "def scatter_two_predictors_side_by_side_with_predictions(X, y, predictor1, predictor2):\n",
    "    fig, axes = plt.subplots(1, 3, figsize=(18,5))\n",
    "    \n",
    "    for i, col in enumerate([predictor1, predictor2]):\n",
    "        x = X[col]\n",
    "        X_const = sm.add_constant(X)\n",
    "        model = sm.OLS(y, X_const).fit()\n",
    "        y_pred = model.predict(X_const)\n",
    "        r2 = r2_score(y, y_pred)\n",
    "        \n",
    "        # Plot scatter and regression line\n",
    "        sorted_idx = x.argsort()\n",
    "        x_sorted = x.iloc[sorted_idx]\n",
    "        y_pred_sorted = y_pred.iloc[sorted_idx]\n",
    "        axes[i].scatter(x, y, label=\"Data\", alpha=0.6)\n",
    "        axes[i].plot(x_sorted, y_pred_sorted, color='red', label=f\"Regression line\\n$R^2={r2:.2f}$\")\n",
    "        axes[i].set_xlabel(col)\n",
    "        axes[i].set_ylabel(\"Y\")\n",
    "        axes[i].set_title(f\"{col} vs Y (full model regression)\")\n",
    "        axes[i].legend()\n",
    "    \n",
    "    # Plot predicted vs observed Y\n",
    "    y_pred_full = sm.OLS(y, sm.add_constant(X)).fit().predict(sm.add_constant(X))\n",
    "    axes[2].scatter(y, y_pred_full, color='green', alpha=0.6, label=\"Predicted vs Observed\")\n",
    "    axes[2].plot([y.min(), y.max()], [y.min(), y.max()], color='black', linestyle='--', label='Perfect prediction')\n",
    "    axes[2].set_xlabel(\"Observed Y\")\n",
    "    axes[2].set_ylabel(\"Predicted Y\")\n",
    "    axes[2].set_title(\"Predicted vs Observed Y\")\n",
    "    axes[2].legend()\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "def plot_residuals_vs_fitted(model, ax=None):\n",
    "    residuals = model.resid\n",
    "    fitted = model.fittedvalues\n",
    "    if ax is None:\n",
    "        fig, ax = plt.subplots(figsize=(6,4))\n",
    "    ax.scatter(fitted, residuals, alpha=0.6)\n",
    "    sns.regplot(x=fitted, y=residuals, lowess=True, ax=ax, line_kws={'color':'red'})\n",
    "    ax.axhline(0, color='black', linestyle='--')\n",
    "    ax.set_xlabel('Fitted values')\n",
    "    ax.set_ylabel('Residuals')\n",
    "    ax.text(0.95,0.05,'Random scatter ~ linearity OK\\nFunnel shape ~ heteroscedasticity',\n",
    "            transform=ax.transAxes, fontsize=9, ha='right', va='bottom', color='blue')\n",
    "    ax.set_title('Residuals vs Fitted')\n",
    "    return ax\n",
    "\n",
    "def plot_scale_location(model, ax=None):\n",
    "    residuals = model.resid\n",
    "    fitted = model.fittedvalues\n",
    "    sqrt_std_resid = np.sqrt(np.abs(residuals / np.std(residuals)))\n",
    "    if ax is None:\n",
    "        fig, ax = plt.subplots(figsize=(6,4))\n",
    "    ax.scatter(fitted, sqrt_std_resid, alpha=0.6)\n",
    "    sns.regplot(x=fitted, y=sqrt_std_resid, lowess=True, ax=ax, line_kws={'color':'red'})\n",
    "    ax.set_xlabel('Fitted values')\n",
    "    ax.set_ylabel('Sqrt(|Standardized Residuals|)')\n",
    "    ax.set_title('Scale-Location')\n",
    "    ax.text(0.95,0.05,'Horizontal ~ constant variance\\nRising/falling ~ heteroscedasticity',\n",
    "            transform=ax.transAxes, fontsize=9, ha='right', va='bottom', color='blue')\n",
    "    return ax\n",
    "\n",
    "def plot_qq(model, ax=None):\n",
    "    residuals = model.resid\n",
    "    if ax is None:\n",
    "        fig, ax = plt.subplots(figsize=(6,4))\n",
    "    sm.qqplot(residuals, line='45', ax=ax)\n",
    "    ax.set_title('Q-Q Plot')\n",
    "    ax.text(0.95,0.05,'Points ~45° line → normal\\nDeviations → non-normality',\n",
    "            transform=ax.transAxes, fontsize=9, ha='right', va='bottom', color='blue')\n",
    "    return ax\n",
    "\n",
    "def plot_residual_autocorrelation(model, show_acf=True, ax=None):\n",
    "    residuals = model.resid\n",
    "    if ax is None:\n",
    "        fig, ax = plt.subplots(figsize=(6,4))\n",
    "    if show_acf:\n",
    "        sm.graphics.tsa.plot_acf(residuals, ax=ax)\n",
    "        ax.set_title('Residual Autocorrelation')\n",
    "        ax.text(0.95,0.05,'Spikes outside CI → dependence\\nOtherwise → independent',\n",
    "                transform=ax.transAxes, fontsize=9, ha='right', va='bottom', color='blue')\n",
    "    else:\n",
    "        ax.scatter(np.arange(len(residuals)), residuals)\n",
    "        ax.axhline(0, color='red', linestyle='--')\n",
    "        ax.set_xlabel('Observation')\n",
    "        ax.set_ylabel('Residuals')\n",
    "        ax.set_title('Residuals vs Observation')\n",
    "        ax.text(0.95,0.05,'Random scatter → independent\\nPatterns → autocorrelation',\n",
    "                transform=ax.transAxes, fontsize=9, ha='right', va='bottom', color='blue')\n",
    "    return ax\n",
    "\n",
    "def plot_residuals_histogram(model, ax=None):\n",
    "    residuals = model.resid\n",
    "    if ax is None:\n",
    "        fig, ax = plt.subplots(figsize=(6,4))\n",
    "    ax.hist(residuals, bins=20, edgecolor='k', alpha=0.7)\n",
    "    ax.set_title(\"Histogram of Residuals\")\n",
    "    ax.set_xlabel(\"Residual\")\n",
    "    ax.set_ylabel(\"Frequency\")\n",
    "    ax.text(0.95, 0.95, \"Bell-shaped → normal\\nSkew/multimodal → non-normal\",\n",
    "            transform=ax.transAxes, fontsize=9, verticalalignment='top',\n",
    "            horizontalalignment='right', color='blue')\n",
    "\n",
    "def plot_diagnostics_annotated(model, show_acf=True):\n",
    "    fig, axs = plt.subplots(2, 3, figsize=(18,10))\n",
    "    \n",
    "    plot_residuals_vs_fitted(model, ax=axs[0,0])\n",
    "    plot_scale_location(model, ax=axs[0,1])\n",
    "    plot_residual_autocorrelation(model, ax=axs[0,2], show_acf=False)  # Residuals vs Observation\n",
    "\n",
    "    plot_qq(model, ax=axs[1,0])\n",
    "    plot_residuals_histogram(model, ax=axs[1,1])\n",
    "    plot_residual_autocorrelation(model, ax=axs[1,2], show_acf=True)  # ACF\n",
    "    plt.tight_layout()\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
